### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by RiverCityBoiii** [MoArtis/RCGMod#1]
Black screen when booting the game
[Desktop.zip](https://github.com/MoArtis/RCGMod/files/3612659/Desktop.zip)

**Comment by MoArtis** [comment]
The error was due to the usage of GetSystemTimePreciseAsFileTime which is not available on Windows versions lower than Win8.
 
Fixed with the latest version! 😉 Thanks @RiverCityBoiii
