### ISSUE TITLE
Enabling/Reenabling localization file import

### ISSUE THREAD

**Issue by winterheart** [MoArtis/RCGMod#11]
Hello.

In Assembly-CSharp.dll exists Data_LocalizationDatabase class which has method LoadLocalizationData() but seems this method unused. Is there any way to reenable it? I need it for translation purposes.

**Comment by MoArtis** [comment]
Should be possible but I sadly don't have much time these days. Hopefully I can look at it again one day.

**Comment by MoArtis** [comment]
Since the update is out and I have some free time, I will try to add a language selection setting for the new version.

**Comment by MoArtis** [comment]
Good news! The internal localization keys and the one in the json file seems to match perfectly so I added an option to choose between the two:
![image](https://user-images.githubusercontent.com/3904610/73002400-f525a180-3e3e-11ea-83de-16fcd461ef6c.png)
That function will be part of the upcoming version.

**Comment by winterheart** [comment]
Cool! Waiting forward for it.

**Comment by winterheart** [comment]
So, this issue solved, I guess...

**Comment by MoArtis** [comment]
@winterheart ahah yes! forgot to write a comment to ask you to test (if you could). Thanks!
