### ISSUE TITLE
Adding mod's name and author in main menu?

### ISSUE THREAD

**Issue by Alua7** [MoArtis/RCGMod#16]
Something like "User Xp mod 1.3 by MoArtis" in the bottom of screen when choosing game slot. 
Would be great for those who don't know about mod but watching streams or letsplays and see new features. And line in ini(config) file like "version info - true/false"

**Comment by MoArtis** [comment]
Ahah ok! Not a big priority but why not. ;) The other contributor must be added (@binhdvo).

**Comment by binhdvo** [comment]
The lionshare of the work has been yours Moartis, I'm happy remaining a helper in the shadows :)

**Comment by MoArtis** [comment]
![image](https://user-images.githubusercontent.com/3904610/73160126-1b8b5b80-4123-11ea-9bac-710a2a3e1ac5.png)

**Comment by Alua7** [comment]
Looking Good :3
