### ISSUE TITLE
Construction Site Cutscene Crash

### ISSUE THREAD

**Issue by RedEyedRocker** [MoArtis/RCGMod#2]
Windows 10 v1809 (OS Build 17763.737)
![River City Girls](https://user-images.githubusercontent.com/22656757/64914580-cd2d7f80-d774-11e9-9547-e7020bc1aa03.jpg)
[output_log.txt](https://github.com/MoArtis/RCGMod/files/3613245/output_log.txt)
[savefile.sav.txt](https://github.com/MoArtis/RCGMod/files/3613528/savefile.sav.txt)

Clean New Save: [savefile.sav.txt](https://github.com/MoArtis/RCGMod/files/3613811/savefile.sav.txt)
Clean New Save Output: [output_log.txt](https://github.com/MoArtis/RCGMod/files/3613808/output_log.txt)

Crashes: [Crashes.zip](https://github.com/MoArtis/RCGMod/files/3613849/Crashes.zip)

**Issue fixed by removing all the "xinput.dll" files and only keeping the "xinput1_4.dll" file for x360ce.**

**Comment by MoArtis** [comment]
[savefile.sav.txt](https://github.com/MoArtis/RCGMod/files/3613536/savefile.sav.txt)

Try this save file.

**Comment by MoArtis** [comment]
[savefile.sav.txt](https://github.com/MoArtis/RCGMod/files/3613568/savefile.sav.txt)

**Comment by MoArtis** [comment]
[Assembly-CSharp.dll.txt](https://github.com/MoArtis/RCGMod/files/3613702/Assembly-CSharp.dll.txt)

**Comment by MoArtis** [comment]
[Assembly-CSharp.dll.txt](https://github.com/MoArtis/RCGMod/files/3613726/Assembly-CSharp.dll.txt)

**Comment by MoArtis** [comment]
Issue fixed by removing all the "xinput.dll" files and only keeping the "xinput1_4.dll" file for x360ce.
