### ISSUE TITLE
GOG .dll

### ISSUE THREAD

**Issue by Alua7** [MoArtis/RCGMod#20]
Assembly-CSharp.dll as requested in main page :o  
[Assembly-CSharp.zip](https://github.com/MoArtis/RCGMod/files/4099904/Assembly-CSharp.zip)

**Comment by MoArtis** [comment]
Ah thank you very much! I will have a look.

**Comment by MoArtis** [comment]
[RCG-UserXpMod_GOG_1.3.zip](https://github.com/MoArtis/RCGMod/files/4123193/RCG-UserXpMod_GOG_1.3.zip)
@Alua7 Can you confirm that this package is working? (or not 😂)

**Comment by Alua7** [comment]
Yup! It's working! Thanks Master! :1st_place_medal:

**Comment by MoArtis** [comment]
Thank you I'm closing it then! 😉
