### ISSUE TITLE
Keep weapons on boss enter

### ISSUE THREAD

**Issue by Alua7** [MoArtis/RCGMod#22]
An option to not to lose current weapon when enter the boss?
Also recruits sometimes disappear when entering the boss(cannot be summoned). 
Situation: 2 players enters yamada - I can summon. He defeats us, I take another recruit - it always disappear(he defeated us several times :D ).

**Comment by MoArtis** [comment]
for the weapons, I can have a look.
For the summon, that sounds like a bug. 🤔 Is that happening using the mod? And you tell me it is inconsistent with Yamada (can summon on first try but then, if another recruit is taken, impossible to summon)? Strange.

**Comment by Alua7** [comment]
Well... https://vk.com/video221048648_456240128 - 1:15:55 - I can summon. 1:28:03 - recruit dissapeared. 1:34:08 - another try.

**Comment by MoArtis** [comment]
We need to check if this is due to the mod or not. Definitely a bug, whatever the source of it. Thanks for the video! 😉

**Comment by Alua7** [comment]
Just in a case it could help.
https://vk.com/video221048648_456240176
We've started experiencing major troubles with recruits. Summoned "King" hang in endless loading and caused noises until we leave location. 
1:03:00 - Riki accidently summons "King" 
1:03:21 - Sound becomes constant
we tried to exit to main menu
1:07:13 - "hanged King"
1:08:40 - Riki takes bad cop and he hangs immediately
1:11:31 - Kunio takes schoolgirl and she hangs
After game restart it fixes.

**Comment by MoArtis** [comment]
@Alua7 Very strange. Is it the same with the passive mod? (I guess since you mentioned that some people experience the same issue without the mod.) Thanks for the video.
@binhdvo this might interests you.

**Comment by MoArtis** [comment]
![image](https://user-images.githubusercontent.com/3904610/73176722-1ab8f080-4148-11ea-8987-168d69089d51.png)
Keeping the weapons while entering boss rooms seems to be working. Might lead to other bugs though. It will require some testing.

**Comment by MoArtis** [comment]
@Alua7 You might want to create a new separate issue for the summon bug. The weapon issue will be close soon as it is part of the 1.3 version of the mod. ;)

**Comment by binhdvo** [comment]
Hey, can you confirm if the recruits bug happens when activeRecruits is false?  What about when not using the mod at all?

**Comment by Alua7** [comment]
tbh I'm refering to discord's dude who was writing "Is anyone else experiencing the recruit button breaking?  Know of any workaround?" and "Rebooting fixes it for me, but that means shutting the entire game down and relaunching; not just returning to the menu screen." when I say "other people too". We had this with similar symptoms so...
I'll try to check inactive recruits and clean game...

**Comment by Alua7** [comment]
Bugs are not detected this far :100:

**Comment by MoArtis** [comment]
I'm closing the main issue (keeping weapons for bosses). If needed don't hesitate to create a new issue for the other recruit bug. Thanks!
