### ISSUE TITLE
Enter/Exit button unhold

### ISSUE THREAD

**Issue by Alua7** [MoArtis/RCGMod#32]
Would be possible to keep entering/leaving areas/shops with just pressing button(not holding)?

**Comment by MoArtis** [comment]
Done and to be tested!

**Comment by MoArtis** [comment]
@Alua7 Don't hesitate to confirm if the fixes/features are working on all the issue you created (or other if you can/wish). Thanks! 😁

**Comment by Alua7** [comment]
I understand :)  And immediately report if anyhing's broken. This one works
