### ISSUE TITLE
Bug that might be related to shared rewards

### ISSUE THREAD

**Issue by Gekasx** [MoArtis/RCGMod#34]
I was testing v1.3 and the second i died my money went from 80 to 9999 (i got the achievement of collecting $5000) and after that my money looks like this
![money](https://user-images.githubusercontent.com/56242846/73301921-8192e400-41f2-11ea-8dc7-4ccca587abda.jpg)

**Comment by Alua7** [comment]
Numbers summed not as numbers?

**Comment by MoArtis** [comment]
@Gekasx So you activated shared rewards? I need to test that.
@Alua7 NaN could be displayed if the number is infinity or is the result of a division by 0 in runtime (iirc Unity doesn't crash at all in that case).

**Comment by MoArtis** [comment]
@Gekasx Can you give me more context? What else did you changed? Were you playing alone or with another player?

**Comment by MoArtis** [comment]
Can't reproduce with a clean install and using Rikki in solo while getting defeated by the first boss.
![image](https://user-images.githubusercontent.com/3904610/73325397-57403580-4289-11ea-9a77-d3673cedcf8e.png)
I need to try in coop. it is certainly related to shared rewards.

**Comment by MoArtis** [comment]
![image](https://user-images.githubusercontent.com/3904610/73325862-1b0dd480-428b-11ea-8d50-074205660c16.png)
🤔 Strange... I'm gonna check the code directly.

**Comment by MoArtis** [comment]
@Gekasx  I changed the shared rewards feature to avoid potential division by 0. I can't be 100% sure that was the source of your issue but I'm pretty sure. Give it a try by re-downloading the pack again (It's updated) and let me know.
https://github.com/MoArtis/RCGMod/releases/tag/1.3

**Comment by Gekasx** [comment]
i tried to replicate the bug with no succes (with the previous version and the new one) i guess it was a super specific situation because the only factor that actually matters was me playing alone after misako's death

**Comment by MoArtis** [comment]
Thank you! I think it should be fine now. I'm gonna close that issue for now.
