### ISSUE TITLE
Bug with the option that skips the title screen

### ISSUE THREAD

**Issue by XZeroName** [MoArtis/RCGMod#4]
-After loading a file, I quit to the menu.

-Pressed Start to skip the logos. (I'm unsure if this step matters.)

-I'm at file select because of the feature that skips the title screen.

-So I press B to go back to title, but the screen transition goes to file select, where I already was.

-One more B to go back and I'm at the title screen this time.

Seems it only happens after loading and quitting.
Starting by skipping to file select and pressing B results in correctly goes back to the title screen.
...Oh, and in case it matters, I'm on file 3. (Well, "File C" as the game calls it.)

**Comment by MoArtis** [comment]
Should be fixed now!
Please redownload the version 1.2 and let me know if it fixes your issue.

**Comment by XZeroName** [comment]
"Save & quit" sent me back to the title screen. It's fixed.
