### ISSUE TITLE
The game doesnt open after installing the mod for v1.0 and suggestion to make a NUDE mod ;)

### ISSUE THREAD

**Issue by CuddleDaddyMick** [MoArtis/RCGMod#51]
is it because my game is cracked and the version is 1.0 instead of 1.1? Please help. TwT

**Comment by MoArtis** [comment]
The mod only works for the latest version of the game (1.1 afaik).

**Comment by CuddleDaddyMick** [comment]
@MoArtis  thanks for letting me know, i just installed your first RCG mod and its working fabulously (tho i dont have the features that the updated mod has duhh but i m quite happy nonetheless). And i would also like to suggest that could you please work on NUDE mod, basically turn the main characters naked. If you actually end up making it im sure your mod would seriously be a hit, as it would make the whole game a lot more fun (infact i would be the first one to install it ;) , provided that its compatible w v1.0 lol ). And yeah thanks again, i appreciate your hard work. much love.

**Comment by MoArtis** [comment]
If you appreciate the game just buy it though. 😂
And for the suggestion:
![image](https://user-images.githubusercontent.com/3904610/91146088-fa0a4680-e6e8-11ea-8161-8aaf0f0764d4.png)
