### ISSUE TITLE
GamePass for PC Compatibility

### ISSUE THREAD

**Issue by vatovato** [MoArtis/RCGMod#52]
Hi! The game has been available for GamePass for a couple of days now and I was wondering if there was any way you could make a version for it. I can't even begin to play the game due to a bug with the DS4 controller, where the Player 2 Join button is mapped to Square, which makes it impossible to play the game with just one girl.

Thank you!

**Comment by MoArtis** [comment]
Can you send me the Assembly-csharp.dll file from that version? I can't promise anything but I will have a look.

**Comment by vatovato** [comment]
> Can you send me the Assembly-csharp.dll file from that version? I can't promise anything but I will have a look.

I would love to but there is no such thing. There isn't even a \RiverCityGirls_Data\Managed folder. Here is a screenshot of all there is:

![Screenshot 2020-11-26 073611](https://user-images.githubusercontent.com/35309563/100340749-692e5a00-2fba-11eb-81ac-02c63eb8bba6.jpg)

**Comment by MoArtis** [comment]
Oh that's a bummer. I'm guessing that the UWP build requires IL2CPP. This not as easy to decompile as Mono. I don't think there is a way to mod that kind of build at the moment. Sorry about that. 😢

**Comment by vatovato** [comment]
Oh that's quite alright. Guess I'll have to get the Steam version. Thanks!
