### ISSUE TITLE
How to mod myself/fix issues?

### ISSUE THREAD

**Issue by Bagels1** [MoArtis/RCGMod#53]
Trying to get UserXpMod to work with this game update version 1, when I paste the unzipped contents into the install directory I replace Assembly-CSharp.dll as instructed but once done the game refuses to run even with admin privelege (starts to open then vanishes). Can MOArtis/anybody help me out? I tried both the steam and GOG versions of the mod and even tried some earlier version of the mod but can't get it to run.

If for some reason I can't get it to run, I really want to try changing some stuff through editing my own local files, I can edit River City Girls\RiverCityGirls_Data\StreamingAssets with a text editor but I don't know how to ad 'NULL' and all the words in black? When I open River City Girls\RiverCityGirls_Data\Managed\Assembly-CSharp.dll with a code editor, does NUL mean true or false, if so how do I write true? Could I just add 'displayDamageOnHit' or "displayhitDmg"? Where in the doc would I place, and what would I add to make it work?

Also are there any other useful mods for this game, I can't find any strangely? Edit: When I updated the game it now works. Thank you so much for your work.

**Comment by MoArtis** [comment]
👍
