### ISSUE TITLE
Special meter bugged?

### ISSUE THREAD

**Issue by Bagels1** [MoArtis/RCGMod#54]
I can recruit enemies fine with L1, but can't actually call them in to help with any button? (I've enabled active recruits)

**Comment by MoArtis** [comment]
Strange. I'm gonna test that myself. Are you using the steam version?

**Comment by MoArtis** [comment]
I just checked and it seems that some enemies can get pretty buggy.
Do you have any more information that you can provide about your issue?

**Comment by Bagels1** [comment]
> I just checked and it seems that some enemies can get pretty buggy.
> Do you have any more information that you can provide about your issue?

GOG. I completed the game now, but the only time I could summon an enemy seemed to happen mysteriously and I couldn't make it happen myself no matter which button I pressed lol. Never mind I enjoyed the mod despite whatever the problem was, so thank you. :)
