### ISSUE TITLE
Game keeps crashing as soon as I open it

### ISSUE THREAD

**Issue by IunarFr** [MoArtis/RCGMod#65]
no matter when i change the files or not, it keeps crashing!

**Comment by IunarFr** [comment]
nevermind, i found out there was 2 same keys in the player controls. i didn't notice.

**Comment by MoArtis** [comment]
🫡

**Comment by IunarFr** [comment]
great mod by the way, and have a nice day:)

**Comment by MoArtis** [comment]
Thanks! Enjoy the mod!
