### ISSUE TITLE
Mod breaks the GOG version

### ISSUE THREAD

**Issue by Zanmato27** [MoArtis/RCGMod#7]
I just installed this mod fresh from GOG and the mod gives me a black screen when I try to start the game and I can't do anything at all except for closing the game with Alt+F4. Can you fix this for GOG players?

**Comment by MoArtis** [comment]
@Zanmato27 Thank you for reporting that issue. 

Try to start the game again with the mod and open the link below with the Explorer or by using the Win key + R :
%userprofile%\appdata\locallow\WayForward Technologies\River City Girls\

Then just drag and drop the output.log file into a new comment on Github. :)
Thanks!

**Comment by HGPMischiefMaker** [comment]
[output_log.txt](https://github.com/MoArtis/RCGMod/files/3720842/output_log.txt)

**Comment by Zanmato27** [comment]
Here's my log file.
[output_log.txt](https://github.com/MoArtis/RCGMod/files/3721212/output_log.txt)

**Comment by MoArtis** [comment]
Apparently they stripped all the steam related scripts (which make sense obviously) thus breaking the references of other scripts. 

Attempting to fix it blindly is unlikely to work. So could one of you @HGPMischiefMaker or @Zanmato27 compress and share the managed folder to me?

**Comment by MoArtis** [comment]
The folder should located here: "River City Girls\RiverCityGirls_Data\Managed"

**Comment by HGPMischiefMaker** [comment]
[Managed.zip](https://github.com/MoArtis/RCGMod/files/3721966/Managed.zip)

**Comment by Zanmato27** [comment]
Here's mine too if it helps:

[Managed.zip](https://github.com/MoArtis/RCGMod/files/3722621/Managed.zip)

**Comment by MoArtis** [comment]
Thank you two! Don't hesitate to add me on steam so we can test a GOG version of the mod quickly.
https://steamcommunity.com/id/MoArtis/

**Comment by MoArtis** [comment]
[RCG-UserXpMod_GOG_1.2_RC1.zip](https://github.com/MoArtis/RCGMod/files/3723008/RCG-UserXpMod_GOG_1.2_RC1.zip)

@Zanmato27 @HGPMischiefMaker  Please try this version of the mod and let me know how it goes. 😀

**Comment by HGPMischiefMaker** [comment]
Looks like it works!  Loaded the game and played around with keyboard controls for a bit.

Thanks so much for doing this!

**Comment by MoArtis** [comment]
oh wow! I'm actually surprised it works!! 😁
The only thing annoying is that I can't think of a way to have only one version of the mod for GOG and Steam. Too bad.
Thanks for the help! @HGPMischiefMaker and @Zanmato27

**Comment by MoArtis** [comment]
I added a download link for that GOG version of the mod.
https://github.com/MoArtis/RCGMod/releases/tag/1.2

I will wait a bit for more feedback / confirmation before closing this issue. 😁

**Comment by Zanmato27** [comment]
I'm still having the black screen problem even with the GOG version of this mod.

**Comment by HGPMischiefMaker** [comment]
Same here.  

The release candidate 1 version works for me, but when I switch to the newer version you linked, the black screen problem is back.

**Comment by MoArtis** [comment]
Ah damn... I need to check what happened. For now I will replace the RC1 with the release version.

@Zanmato27 What do you mean by grab button? Grabbing is automatic in the game. 🤔
For the statistics, while it is feasible I don't think it worth the effort. The gameobject displaying the text is actually refurbished debug text so I prefer not taking more risks with it since it works pretty well. 😁 And also I don't have enough time to work on the mod these days.

**Comment by MoArtis** [comment]
@Zanmato27 @HGPMischiefMaker Ah! I think I just made a small stupid mistake with the release version.

Please test this version and let me know if it's working: 
[RCG-UserXpMod_GOG_1.2_RC2.zip](https://github.com/MoArtis/RCGMod/files/3727171/RCG-UserXpMod_GOG_1.2_RC2.zip)

**Comment by Zanmato27** [comment]
It's the button to grab objects, and when you have the Human Weapon skill, it counts towards people too, and with the button changed, you can't grabbed downed people anymore with the original button.

**Comment by MoArtis** [comment]
@Zanmato27 @HGPMischiefMaker Are you two still around? I need your help to get us the updated managed files from the GOG version. 😁

I also need to have a serious look on the two little issues reported by @Zanmato27. Can you create two new separate issues for them?
