### ISSUE TITLE
Feature Request: Disable moves

### ISSUE THREAD

**Issue by True-Khaos** [MoArtis/RCGMod#8]
I don't know how complicated this would be but it would be amazing to be able to turn off moves you don't use. I would love to disable cheer drill on Kyoko so I can pull off Volleyball Strike more consistently.

**Comment by MoArtis** [comment]
The logic should be feasible but the UI will be terribly painful to make (as we are only modifying the code of an editor-driven engine, Unity). 
And listing all the moves and their activation flag in the config file sounds very sad and annoying for the end-user. 🤔

I can't promise anything but I will keep that feature request around. Thanks for the proposition! 😃

**Comment by binhdvo** [comment]
As MoArtis says, this is doable in logic; the config file format for it might be better done as making a list of inputs for the move(s) you want disabled.  I should point out though, that for your particular case I do not believe it will help what you are trying to do; volleyball strike already outprioritizes cheer drill on the input processing, so if the game does cheer drill it means it has already decided you didn't hit the window for the strike.

I think more likely, you are running afoul of the bug where fps rates in excess of 60 can make the air throw window more difficult.  The mod has some options to help address this, have you tried those?

**Comment by True-Khaos** [comment]
I'm a little late on the river city girls train as I just got the game this week and found the mod today. I'll have to try limiting my framerate when I get time, wasn't aware that that was a potential problem.
I figured this feature might be a little difficult but thanks for the positive feedback right away, both about the feature itself and my apparently unrelated issue.

**Comment by MoArtis** [comment]
@True-Khaos Are you still around? Did limiting the framerate helped you to pull off the right moves?

**Comment by True-Khaos** [comment]
@MoArtis It may have helped a little bit, honestly I was probably just not great at nailing that window. My success rate fluctuated as I played. I think I was a little more consistent after limiting the framerate though

**Comment by MoArtis** [comment]
Ok good to know! I'm gonna close that issue for now. But don't hesitate to add more info about if needed. I might reopen it later in that case.
