### ISSUE TITLE
Missing Chinese UI

### ISSUE THREAD

**Issue by jeeyi345** [MoArtis/RCGMod#9]
Hi, thank you for the mod! Helps a lot in game play.
I noticed that  Chinese UI disappeared after replace dll with the modded dll.
Please help me with the issue if you have free time. I got so used to the mod I feel uncomfortable when playing stock Chinese.

**Comment by MoArtis** [comment]
Oh that's strange. 
I need to look into how localization works in that RCG.
Thanks for reporting the issue.

**Comment by jeeyi345** [comment]
Some findings - If I start the game in default English and mod applied, Chinese (CJK actually) hidden, but if I switch to Chinese then applied the mod, Chinese UI and mod effects stays. If I switch language in game, CJK will be gone.

**Comment by MoArtis** [comment]
Probably related to https://github.com/MoArtis/RCGMod/issues/11
I will look into it for the new version. Thanks again for reporting the issue!

**Comment by jeeyi345** [comment]
Not at all. Thank you for the effort!

**Comment by MoArtis** [comment]
![RCGMod_LanguageFix](https://user-images.githubusercontent.com/3904610/72881366-99bebb00-3d3b-11ea-897e-ce83481f03d9.gif)

@jeeyi345 It should now be fixed in the latest version of the mod.
https://github.com/MoArtis/RCGMod/releases

**Comment by jeeyi345** [comment]
Thank you!
I'm on holiday (Chinese / Lunar new year), I'll try it next week.

**Comment by MoArtis** [comment]
Happy Chinese new year! 😁 I'm currently doing it too, in Wuhan 👀💦 ahah!

**Comment by jeeyi345** [comment]
Happy Chinese new year, 😲take care, stay safe!

**Comment by jeeyi345** [comment]
> @jeeyi345 It should now be fixed in the latest version of the mod.
> https://github.com/MoArtis/RCGMod/releases
> Please give it a try and let me know if this fix your issue. 😁
> ![RCGMod_LanguageFix](https://user-images.githubusercontent.com/3904610/72881366-99bebb00-3d3b-11ea-897e-ce83481f03d9.gif)

Tried it today, works perfectly, can't wait to beat it again!
Thank you!

**Comment by MoArtis** [comment]
Thank you! I'm closing the issue then. 😀
